# Generated by Django 4.1 on 2024-10-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='Email',
            new_name='email',
        ),
    ]
